modLoader="javafml"
loaderVersion="[42,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/ItemResistance/issues"

[[mods]]
	modId="itemresistance"
	version="${file.jarVersion}"
	displayName="ItemResistance"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/itemresistance.json"
	displayURL="https://apexstudios.dev/apexcore"
	# logoFile="banner.png"
	credits="Apex - Programming"
	authors="Apex"
	description="Stops dropped items from exploding"
	displayTest="MATCH_VERSION"

[[dependencies.itemresistance]]
	modId="forge"
	mandatory=true
	versionRange="[42.0.2,43.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.1,1.20)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="commonality"
	mandatory=true
	versionRange="[3.0.0,4.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="apexcore"
	mandatory=false
	versionRange="[6.0.0,7.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"