modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/ItemResistance/issues"

[[mods]]
	modId="itemresistance"
	version="${file.jarVersion}"
	displayName="ItemResistance"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/itemresistance.json"
	displayURL="https://apexstudios.dev/apexcore"
	# logoFile="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="Stops dropped items from exploding"
	displayTest="MATCH_VERSION"

[[dependencies.itemresistance]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.60,41)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="commonality"
	mandatory=true
	versionRange="[1.2.1,2.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="apexcore"
	mandatory=false
	versionRange="[4.10.0,5.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"