modLoader="javafml"
loaderVersion="${forge_version_range}"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexModder/ItemResistance/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/ApexModder/Version/master/itemresistance.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/itemresistance"
    # logoFile="banner.png"
    # credits=""
    authors="${mod_authors}"
    description="Stops dropped items from exploding"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="${devworld_mod_id}"
    mandatory=false
    versionRange="${devworld_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="${smoothboot_mod_id}"
    mandatory=false
    versionRange="${smoothboot_version_range}"
    ordering="AFTER"
    side="BOTH"