modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/ItemResistance/issues"

[[mods]]
	modId="itemresistance"
	version="${file.jarVersion}"
	displayName="ItemResistance"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/itemresistance.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/itemresistance"
	# logoFile="banner.png"
	credits="Apex - Programming"
	authors="Apex"
	description="Stops dropped items from exploding"
	displayTest="MATCH_VERSION"

[[dependencies.itemresistance]]
	modId="forge"
	mandatory=true
	versionRange="[41.0.98,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.itemresistance]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19,1.20)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.itemresistance]]
	modId="commonality"
	mandatory=true
	versionRange="[2.2.0,3.0.0)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.itemresistance]]
	modId="apexcore"
	mandatory=false
	versionRange="[5.0.0,6.0.0)"
	ordering="AFTER"
	side="BOTH"