modLoader="javafml"
loaderVersion="[44,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="itemresistance"
	version="${file.jarVersion}"
	displayName="ItemResistance"
	updateJSONURL="https://api.modrinth.com/updates/itemresistance/forge_updates.json"
	displayURL="https://apexstudios.dev/apexcore"
	# logoFile="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="Stops dropped items from exploding"
	displayTest="MATCH_VERSION"

[[dependencies.itemresistance]]
	modId="forge"
	mandatory=true
	versionRange="[44.0.0,45.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.3,1.19.4)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="commonality"
	mandatory=true
	versionRange="[5.0.0,6.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		ignore=true
[[dependencies.itemresistance]]
	modId="apexcore"
	mandatory=false
	versionRange="[8.0.0,9.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.itemresistance.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"
