modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/ItemResistance/issues"

[[mods]]
	modId="itemresistance"
	version="${file.jarVersion}"
	displayName="ItemResistance"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/itemresistance.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/itemresistance"
	authors="Apex"
	description="Stops dropped items from exploding"

[[dependencies.itemresistance]]
	modId="forge"
	mandatory=true
	versionRange="[40,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.itemresistance]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,)"
	ordering="AFTER"
	side="BOTH"