modLoader="javafml"
loaderVersion="[4,)"
license="AllRightsReserved"

[[mods]]
    modId="itemresistance"
    version="${file.jarVersion}"
    displayName="ItemResistance"
    credits="Apex - Programming"
    authors="ApexStudios"
    description="ItemResistance"

[[dependencies.itemresistance]]
    modId="apexcore"
    type="required"
    versionRange="[21.4,)"

#[[accessTransformers]]
#    file="META-INF/accesstransformer.cfg"
[[mixins]]
   config="META-INF/itemresistance.mixins.json"