license = "AllRightsReserved"
issueTrackerURL = "https://github.com/ApexStudios-Dev/Issues/issues"

[[mods]]
modId = "itemresistance"
version = "${file.jarVersion}"
displayName = "ItemResistance"
credits = "Apex - Programming"
authors = "ApexStudios"
description = "ItemResistance is a simple mod which allows dropped block items to resist explosions."
logoFile = "banner.png"
iconFile = "logo.png"
displayURL = "https://modrinth.com/mod/itemresistance"

[[dependencies.itemresistance]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"
[[dependencies.itemresistance]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemresistance]]
modId = "apexcore"
type = "required"
versionRange = "[26.1,26.2)"
[dependencies.itemresistance.mc-publish]
modrinth = "xl3myxch"
curseforge = "550778"

#[[accessTransformers]]
#    file="META-INF/accesstransformer.cfg"
[[mixins]]
config = "META-INF/itemresistance.mixins.json"
