modLoader="javafml"
loaderVersion="[${NEOFORGE_LOADER_VERSION},)"
license="${MOD_LICENSE}"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="${MOD_ID}"
	version="${MOD_VERSION}"
	displayName="${MOD_NAME}"
	updateJSONURL="https://api.modrinth.com/updates/${MOD_ID}/forge_updates.json"
	displayURL="https://apexstudios.dev/${MOD_ID}"
	logoFile="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="${MOD_DESCRIPTION}"
	displayTest="MATCH_VERSION"

[features."${MOD_ID}"]
	javaVersion="${JAVA_VERSION}"

[[dependencies."${MOD_ID}"]]
	modId="forge"
	mandatory=true
	versionRange="${NEOFORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}"]]
	modId="minecraft"
	mandatory=true
	versionRange="${MINECRAFT_NEOFORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}"]]
	modId="${APEXCORE_ID}"
	mandatory=true
	versionRange="${APEXCORE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
