name: Check Local Changes

on:
    pull_request:
        types:
            - synchronize
            - opened
            - ready_for_review
            - reopened
        branches:
            - '!**/port'

jobs:
    check-local-changes:
        name: Check Local Changes
        uses: ApexStudios-Dev/.github/.github/workflows/check-local-changes.yml@master
