name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ '**/main' ]
    paths: [ '**/src/**' ]

jobs:
  publish-mod:
    uses: ApexStudios-Dev/.github/.github/workflows/_publish-mod.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      publish-task: ':publishReleasePublicationToApexStudios-ReleasesRepository'
      curseforge-id: '835372' # '416161'
      modrinth-id: 'EjjiYArZ' # 'XDyegkJL'
      artifact-id: itemresistance
      display-name: ItemResistance
      release-type: release
      logo-url: 'https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/minecraft/itemresistance/logo.png'
      color: 0xB50E0E
