name: Publish Assets

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-vars:
    name: Generate Vars
    uses: ApexStudios-Dev/.github/.github/workflows/_generate-vars.yml@master
    secrets: inherit

  publish-assets:
    name: Publish Assets
    runs-on: ubuntu-latest
    needs: generate-vars
    steps:
      - name: Publish assets
        uses: ApexStudios-Dev/.github/actions/publish-assets@master
        with:
          mod-name: ItemResistance
          mod-id: itemresistance
          mod-version: ${{ needs.generate-vars.outputs.version }}
          mod-src-dir: src
