on:
    workflow_dispatch:
    push:
        branches: [ "**/main" ]
        paths: [ "**/src/**" ]

jobs:
    publish:
        uses: ApexStudios-Dev/.github/.github/workflows/publish-mod.yml@master
        secrets:
            MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
            CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
#            MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
