name: Test PR

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened

jobs:
  compile-mod:
    name: Compile Mod
    runs-on: apexstudios
    steps:
      - name: Checkout Repository
        id: checkout
        uses: ApexStudios-Dev/.github/actions/checkout@master

      - name: Setup Java
        uses: ApexStudios-Dev/.github/actions/setup-java@master

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@master

      - name: Build with Gradle
        run: ./gradlew :build
        env:
          VERSION: ${{ steps.checkout.outputs.version }}

      - name: Delete unwanted artifacts
        if: success()
        run: rm -rf ./build/libs/*-data*jar ./build/libs/*-sources*jar

      - name: Upload Mod
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: production-artifacts
          path: ./build/libs/*-${{ steps.checkout.outputs.version }}.jar
          if-no-files-found: error

  download-dependencies:
    name: Download Dependencies
    needs: compile-mod
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Download Mod
        uses: actions/download-artifact@v4
        with:
          name: production-artifacts

      - name: Download Dependencies
        run: wget https://maven.apexstudios.dev/releases/dev/apexstudios/apexcore/$APEXCORE_VERSION/apexcore-$APEXCORE_VERSION.jar
        env:
          APEXCORE_VERSION: 21.5.2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-artifacts
          path: '*.jar'
          if-no-files-found: error
          overwrite: true

  test-production-server:
    name: Test Production Server
    uses: ApexStudios-Dev/.github/.github/workflows/test-production-server.yml@master
    needs: download-dependencies
    if: success()
    with:
      neoforge_version: 21.5.0-beta
