name: Test PR

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  generate-vars:
    name: Generate Vars
    uses: ApexStudios-Dev/.github/.github/workflows/_generate-vars.yml@master
    secrets: inherit

  build:
    name: Build
    needs: generate-vars
    if: success()
    uses: ApexStudios-Dev/.github/.github/workflows/_build.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      version: ${{ needs.generate-vars.outputs.version }}

  check-local-changes:
    name: Check local changes
    needs: generate-vars
    if: success()
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      version: ${{ needs.generate-vars.outputs.version }}

  publish-maven:
    name: Publish Maven
    needs: [ generate-vars, build, check-local-changes ]
    if: success()
    uses: ApexStudios-Dev/.github/.github/workflows/_publish-maven.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      version: ${{ needs.generate-vars.outputs.version }}
      publish-task: ':publishReleasePublicationToApexStudios-PrivateRepository'

  test:
    name: Test Production
    runs-on: ubuntu-latest
    needs: [ generate-vars, publish-maven ]
    if: success()
    steps:
      - name: Prepare Environment
        run: |
          mkdir mods
          wget -O "mods/apexcore-$APEXCORE_VERSION.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/apexcore/$APEXCORE_VERSION/apexcore-$APEXCORE_VERSION.jar"
          wget -O "mods/itemresistance-${{ needs.generate-vars.outputs.version }}.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/itemresistance/${{ needs.generate-vars.outputs.version }}/itemresistance-${{ needs.generate-vars.outputs.version }}.jar"
        env:
          APEXCORE_VERSION: 21.9.1-beta-pr-49

      - name: Test Production Server
        uses: ApexStudios-Dev/.github/actions/test-production-server@master
        with:
          java-version: 21
          java-vendor: temurin
          neoforge-version: 21.9.0-alpha.25w34b.20250821.203312
          neoforge-maven: 'https://maven.apexstudios.dev/private'
